# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cd653c249292b78010f157bf4b4d21c8"
name = "ChatasBot"
application_url = "https://cab.chatasbot.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demossss-2.myshopify.com"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/api/v1/shopify/webhook/compliance-topics"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update", "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create", "checkouts/update" ]
  uri = "/webhooks/checkouts"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_customers,read_draft_orders,read_merchant_managed_fulfillment_orders,read_order_edits,read_orders,read_payment_customizations,read_product_feeds,read_product_listings,write_assigned_fulfillment_orders,write_customers,write_draft_orders,write_merchant_managed_fulfillment_orders,write_order_edits,write_orders,write_payment_customizations,write_payment_terms,write_product_feeds,write_product_listings"
optional_scopes = [
  "read_products",
  "write_products",
  "read_publications",
  "write_publications",
  "read_translations"
]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://cab.chatasbot.com/auth/callback",
  "https://cab.chatasbot.com/auth/shopify/callback",
  "https://cab.chatasbot.com/api/auth/callback"
]
